# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-08 20:40
from __future__ import unicode_literals

import aC_bookfest.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('photo', models.FileField(upload_to=aC_bookfest.models.user_directory_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=aC_bookfest.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('s_Title', models.CharField(blank=True, max_length=255)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('Website', models.CharField(blank=True, max_length=255)),
                ('Location', models.CharField(blank=True, max_length=255)),
                ('s_Location', models.CharField(blank=True, max_length=255)),
                ('Time', models.CharField(blank=True, max_length=100)),
                ('s_Time', models.CharField(blank=True, max_length=100)),
                ('Description', models.TextField(blank=True, max_length=10000)),
                ('OfferType', models.CharField(blank=True, max_length=100)),
                ('s_OfferType', models.CharField(blank=True, max_length=100)),
                ('Max_order', models.IntegerField(blank=True, null=True)),
                ('Picture', models.FileField(blank=True, default='settings.MEDIA_ROOT/default.jpg', null=True, upload_to=aC_bookfest.models.event_pic_path)),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, to='aC_bookfest.Event')),
                ('user', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('order_checkin', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('favorites', models.ManyToManyField(related_name='favorited_by', to='aC_bookfest.Event')),
                ('orders', models.ManyToManyField(through='aC_bookfest.Order', to='aC_bookfest.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Profile',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='aC_bookfest.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='aC_bookfest.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aC_bookfest.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
