# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-08 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='s_Location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='s_OfferType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='s_Time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='s_Title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
