# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0003_auto_20180411_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
