# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0004_order_order_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
