# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0005_auto_20180412_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested',
            name='event',
        ),
        migrations.RemoveField(
            model_name='interested',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_checkin',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_confirm',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Interested',
        ),
    ]
