# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0006_auto_20180319_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aC_bookfest.Event'),
        ),
    ]
