# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0007_auto_20180319_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, to='aC_bookfest.Event'),
        ),
    ]
