# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0007_auto_20180413_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
