# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0011_auto_20180322_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
