# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 22:43
from __future__ import unicode_literals

import aC_bookfest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0012_auto_20180322_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Picture',
            field=models.FileField(null=True, upload_to=aC_bookfest.models.event_pic_path),
        ),
    ]
