# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0014_auto_20180322_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='aC_bookfest.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(through='aC_bookfest.Order', to='aC_bookfest.Event'),
        ),
    ]
