# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0015_auto_20180324_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Type',
            field=models.CharField(default='event', max_length=100),
            preserve_default=False,
        ),
    ]
