# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0016_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
