# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0017_event_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Time',
            field=models.CharField(max_length=100),
        ),
    ]
