# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0018_auto_20180403_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
