# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0019_auto_20180403_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Cost',
        ),
        migrations.AddField(
            model_name='event',
            name='OfferType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
