# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0020_auto_20180403_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Organizer',
        ),
    ]
