# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0022_auto_20180406_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
