# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-08 18:41
from __future__ import unicode_literals

import aC_bookfest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0023_remove_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Max_order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Picture',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/default.jpg', null=True, upload_to=aC_bookfest.models.event_pic_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='Time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
