# Generated by Django 2.0.4 on 2018-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aC_bookfest', '0024_auto_20180408_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Max_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
